[package]
name = "test-ui"
version = "0.1.0"
edition = "2021"
publish = false

repository = "https://github.com/madsmtm/objc2"
license = "MIT"

[lints]
workspace = true

[features]
# UI tests don't work without `Foundation` feature, but we have no way of
# specifying that, as trybuild doesn't take any arguments
default = [
    "apple",
    "std",
    "objc2-foundation/block2",
    "objc2-foundation/Foundation_NSObjCRuntime",
    "objc2-foundation/Foundation_NSString",
    "objc2-foundation/Foundation_NSNotification",
    "objc2-foundation/Foundation_NSThread",
    "objc2-foundation/Foundation_NSError",
    "objc2-foundation/Foundation_NSArray",
    "objc2-foundation/Foundation_NSValue",
    "objc2-foundation/Foundation_NSSet",
    "objc2-foundation/Foundation_NSObject",
    "objc2-foundation/Foundation_NSURLSession",
    "objc2-foundation/Foundation_NSEnumerator",
    "objc2-foundation/Foundation_NSDictionary",
    "objc2/unstable-msg-send-always-comma",
]
std = ["block2/std", "objc2/std", "objc2-foundation/std"]

apple = ["block2/apple", "objc2/apple", "objc2-foundation/apple"]
gnustep-1-7 = ["block2/gnustep-1-7", "objc2/gnustep-1-7", "objc2-foundation/gnustep-1-7"]
gnustep-1-8 = ["gnustep-1-7", "block2/gnustep-1-8", "objc2/gnustep-1-8", "objc2-foundation/gnustep-1-8"]
gnustep-1-9 = ["gnustep-1-8", "block2/gnustep-1-9", "objc2/gnustep-1-9", "objc2-foundation/gnustep-1-9"]
gnustep-2-0 = ["gnustep-1-9", "block2/gnustep-2-0", "objc2/gnustep-2-0", "objc2-foundation/gnustep-2-0"]
gnustep-2-1 = ["gnustep-2-0", "block2/gnustep-2-1", "objc2/gnustep-2-1", "objc2-foundation/gnustep-2-1"]

run = ["trybuild"]

[dependencies]
trybuild = { version = "1.0.72", optional = true }
block2 = { path = "../block2", default-features = false }
objc2 = { path = "../objc2", default-features = false }
objc2-foundation = { path = "../../framework-crates/objc2-foundation", default-features = false }

[[bin]]
name = "test-ui"
required-features = ["run"]
