[[example]]
name = "browser"
required-features = [
    "objc2-app-kit",
    "objc2-app-kit/AppKit_NSResponder",
    "objc2-app-kit/AppKit_NSView",
    "objc2-app-kit/AppKit_NSColor",
    "objc2-app-kit/AppKit_NSButton",
    "objc2-app-kit/AppKit_NSButtonCell",
    "objc2-app-kit/AppKit_NSMenu",
    "objc2-app-kit/AppKit_NSMenuItem",
    "objc2-app-kit/AppKit_NSStackView",
    "objc2-app-kit/AppKit_NSText",
    "objc2-app-kit/AppKit_NSTextField",
    "objc2-app-kit/AppKit_NSTextView",
    "objc2-app-kit/AppKit_NSWindow",
    "objc2-app-kit/AppKit_NSControl",
    "objc2-app-kit/AppKit_NSApplication",
    "objc2-app-kit/AppKit_NSRunningApplication",
    "objc2-app-kit/AppKit_NSGraphics",
    "objc2-app-kit/AppKit_NSLayoutConstraint",
    "objc2-app-kit/AppKit_NSUserInterfaceLayout",
    "objc2-foundation/Foundation_NSString",
    "objc2-foundation/Foundation_NSGeometry",
    "objc2-foundation/Foundation_NSNotification",
    "objc2-foundation/Foundation_NSURL",
    "objc2-foundation/Foundation_NSURLRequest",
    "objc2-foundation/Foundation_NSThread",
    "WebKit_WKNavigation",
    "WebKit_WKNavigationDelegate",
    "WebKit_WKWebView",
]
